export interface ToolSeed {
  key: string;
  title: string;
  description: string;
  icon: string;
}

export type ShortcutSeed = [
  tool: string,
  level: number,
  description: string,
  expected: string[],
];

export const TOOLS: ToolSeed[] = [
  {
    key: 'general',
    title: 'Atajos generales',
    description: 'Copia, pega, deshacer y guardar. La base de cualquier editor.',
    icon: 'Keyboard',
  },
  {
    key: 'vscode',
    title: 'Visual Studio Code',
    description: 'Paleta de comandos, formateo, multi-cursor y navegación.',
    icon: 'Code',
  },
  {
    key: 'chrome',
    title: 'Google Chrome',
    description: 'Pestañas, historial, descargas y modo incógnito.',
    icon: 'Globe',
  },
  {
    key: 'word',
    title: 'Microsoft Word',
    description: 'Formato de texto, estilos y navegación del documento.',
    icon: 'FileText',
  },
  {
    key: 'excel',
    title: 'Microsoft Excel',
    description: 'Celdas, fórmulas, selección y navegación de hojas.',
    icon: 'Table',
  },
  {
    key: 'terminal',
    title: 'Terminal',
    description: 'Línea de comandos: cancelar, limpiar e historial.',
    icon: 'Terminal',
  },
  {
    key: 'youtube',
    title: 'YouTube',
    description: 'Reproducción, volumen y navegación del video.',
    icon: 'Play',
  },
  {
    key: 'discord',
    title: 'Discord',
    description: 'Canales, micrófono, búsqueda y marcar como leído.',
    icon: 'MessageCircle',
  },
  {
    key: 'drive',
    title: 'Google Drive',
    description: 'Crear, navegar y organizar tus archivos.',
    icon: 'HardDrive',
  },
  {
    key: 'windows',
    title: 'Windows',
    description: 'Escritorio virtual, bloqueo, captura y administrador de tareas.',
    icon: 'MonitorSmartphone',
  },
];

export const SHORTCUTS: ShortcutSeed[] = [
  ['general', 1, 'Copiar texto seleccionado', ['Control', 'c']],
  ['general', 1, 'Pegar contenido', ['Control', 'v']],
  ['general', 1, 'Cortar selección', ['Control', 'x']],
  ['general', 1, 'Guardar', ['Control', 's']],
  ['general', 2, 'Deshacer última acción', ['Control', 'z']],
  ['general', 2, 'Rehacer', ['Control', 'y']],
  ['general', 2, 'Buscar texto', ['Control', 'f']],
  ['general', 2, 'Seleccionar todo', ['Control', 'a']],
  ['general', 2, 'Poner en negrita', ['Control', 'b']],
  ['general', 3, 'Reemplazar texto', ['Control', 'h']],
  ['general', 3, 'Imprimir', ['Control', 'p']],
  ['general', 3, 'Ir al principio del documento', ['Control', 'Home']],
  ['general', 3, 'Ir al final del documento', ['Control', 'End']],
  ['general', 3, 'Guardar como', ['Control', 'Shift', 's']],
  ['general', 4, 'Seleccionar desde el cursor hasta el inicio', ['Control', 'Shift', 'Home']],
  ['general', 4, 'Seleccionar desde el cursor hasta el final', ['Control', 'Shift', 'End']],

  ['vscode', 1, 'Guardar archivo', ['Control', 's']],
  ['vscode', 1, 'Copiar línea', ['Control', 'c']],
  ['vscode', 1, 'Cortar línea', ['Control', 'x']],
  ['vscode', 2, 'Abrir archivo rápidamente', ['Control', 'p']],
  ['vscode', 2, 'Comentar línea', ['Control', '/']],
  ['vscode', 2, 'Buscar en el archivo', ['Control', 'f']],
  ['vscode', 2, 'Reemplazar en el archivo', ['Control', 'h']],
  ['vscode', 2, 'Formatear documento', ['Shift', 'Alt', 'f']],
  ['vscode', 2, 'Renombrar símbolo', ['F2']],
  ['vscode', 3, 'Abrir la paleta de comandos', ['Control', 'Shift', 'p']],
  ['vscode', 3, 'Buscar en todo el proyecto', ['Control', 'Shift', 'f']],
  ['vscode', 3, 'Abrir la terminal integrada', ['Control', '`']],
  ['vscode', 3, 'Ir a una línea', ['Control', 'g']],
  ['vscode', 3, 'Abrir la configuración', ['Control', ',']],
  ['vscode', 4, 'Duplicar la línea hacia abajo', ['Shift', 'Alt', 'ArrowDown']],
  ['vscode', 4, 'Mover la línea hacia arriba', ['Alt', 'ArrowUp']],
  ['vscode', 4, 'Mover la línea hacia abajo', ['Alt', 'ArrowDown']],
  ['vscode', 4, 'Seleccionar la siguiente coincidencia', ['Control', 'd']],

  ['chrome', 1, 'Abrir nueva pestaña', ['Control', 't']],
  ['chrome', 1, 'Cerrar pestaña actual', ['Control', 'w']],
  ['chrome', 1, 'Abrir nueva ventana', ['Control', 'n']],
  ['chrome', 2, 'Reabrir última pestaña cerrada', ['Control', 'Shift', 't']],
  ['chrome', 2, 'Ir a la barra de direcciones', ['Control', 'l']],
  ['chrome', 2, 'Recargar la página', ['Control', 'r']],
  ['chrome', 2, 'Buscar en la página', ['Control', 'f']],
  ['chrome', 2, 'Marcar como favorito', ['Control', 'd']],
  ['chrome', 3, 'Abrir modo incógnito', ['Control', 'Shift', 'n']],
  ['chrome', 3, 'Abrir el historial', ['Control', 'h']],
  ['chrome', 3, 'Abrir las descargas', ['Control', 'j']],
  ['chrome', 3, 'Ir a la pestaña siguiente', ['Control', 'Tab']],
  ['chrome', 3, 'Mostrar u ocultar la barra de favoritos', ['Control', 'Shift', 'b']],
  ['chrome', 4, 'Ir a la pestaña 5', ['Control', '5']],
  ['chrome', 4, 'Cerrar la ventana', ['Control', 'Shift', 'w']],
  ['chrome', 4, 'Abrir herramientas de desarrollo', ['Control', 'Shift', 'i']],

  ['word', 1, 'Poner en negrita', ['Control', 'b']],
  ['word', 1, 'Poner en cursiva', ['Control', 'i']],
  ['word', 1, 'Subrayar', ['Control', 'u']],
  ['word', 1, 'Guardar', ['Control', 's']],
  ['word', 2, 'Centrar el párrafo', ['Control', 'e']],
  ['word', 2, 'Alinear a la izquierda', ['Control', 'l']],
  ['word', 2, 'Alinear a la derecha', ['Control', 'r']],
  ['word', 2, 'Justificar el párrafo', ['Control', 'j']],
  ['word', 2, 'Copiar el formato', ['Control', 'Shift', 'c']],
  ['word', 3, 'Pegar el formato', ['Control', 'Shift', 'v']],
  ['word', 3, 'Aplicar Título 1', ['Control', 'Alt', '1']],
  ['word', 3, 'Aplicar Título 2', ['Control', 'Alt', '2']],
  ['word', 3, 'Insertar salto de página', ['Control', 'Enter']],
  ['word', 3, 'Quitar el formato del texto', ['Control', 'Shift', 'n']],
  ['word', 4, 'Aumentar el tamaño de fuente', ['Control', 'Shift', '>']],
  ['word', 4, 'Disminuir el tamaño de fuente', ['Control', 'Shift', '<']],

  ['excel', 1, 'Editar la celda activa', ['F2']],
  ['excel', 1, 'Copiar', ['Control', 'c']],
  ['excel', 1, 'Pegar', ['Control', 'v']],
  ['excel', 2, 'Guardar', ['Control', 's']],
  ['excel', 2, 'Insertar la fecha de hoy', ['Control', ';']],
  ['excel', 2, 'Seleccionar la columna', ['Control', 'Space']],
  ['excel', 2, 'Seleccionar la fila', ['Shift', 'Space']],
  ['excel', 2, 'Buscar', ['Control', 'f']],
  ['excel', 3, 'Ir al borde de los datos (derecha)', ['Control', 'ArrowRight']],
  ['excel', 3, 'Seleccionar hasta el borde de los datos', ['Control', 'Shift', 'ArrowRight']],
  ['excel', 3, 'Ir a la celda A1', ['Control', 'Home']],
  ['excel', 3, 'Abrir formato de celdas', ['Control', '1']],
  ['excel', 3, 'Autosuma', ['Alt', '=']],
  ['excel', 4, 'Referencia absoluta ($)', ['F4']],
  ['excel', 4, 'Insertar filas o columnas', ['Control', 'Shift', '+']],

  ['terminal', 1, 'Cancelar el comando actual', ['Control', 'c']],
  ['terminal', 1, 'Limpiar la pantalla', ['Control', 'l']],
  ['terminal', 2, 'Buscar en el historial', ['Control', 'r']],
  ['terminal', 2, 'Ir al inicio de la línea', ['Control', 'a']],
  ['terminal', 2, 'Ir al final de la línea', ['Control', 'e']],
  ['terminal', 3, 'Borrar hasta el inicio de la línea', ['Control', 'u']],
  ['terminal', 3, 'Borrar hasta el final de la línea', ['Control', 'k']],
  ['terminal', 3, 'Borrar la palabra anterior', ['Control', 'w']],
  ['terminal', 3, 'Cerrar la sesión (EOF)', ['Control', 'd']],
  ['terminal', 4, 'Suspender el proceso', ['Control', 'z']],
  ['terminal', 4, 'Pegar en la terminal', ['Control', 'Shift', 'v']],

  ['youtube', 1, 'Reproducir o pausar', ['k']],
  ['youtube', 1, 'Silenciar', ['m']],
  ['youtube', 1, 'Pantalla completa', ['f']],
  ['youtube', 2, 'Retroceder 10 segundos', ['j']],
  ['youtube', 2, 'Adelantar 10 segundos', ['l']],
  ['youtube', 2, 'Activar el modo cine', ['t']],
  ['youtube', 2, 'Activar los subtítulos', ['c']],
  ['youtube', 3, 'Subir el volumen', ['ArrowUp']],
  ['youtube', 3, 'Bajar el volumen', ['ArrowDown']],
  ['youtube', 3, 'Retroceder 5 segundos', ['ArrowLeft']],
  ['youtube', 3, 'Adelantar 5 segundos', ['ArrowRight']],
  ['youtube', 3, 'Abrir el mini reproductor', ['i']],
  ['youtube', 4, 'Ir al video siguiente', ['Shift', 'n']],
  ['youtube', 4, 'Ir al inicio del video', ['0']],

  ['discord', 1, 'Búsqueda rápida (saltar a)', ['Control', 'k']],
  ['discord', 2, 'Silenciar el micrófono', ['Control', 'Shift', 'm']],
  ['discord', 2, 'Silenciar el sonido', ['Control', 'Shift', 'd']],
  ['discord', 2, 'Abrir la lista de atajos', ['Control', '/']],
  ['discord', 2, 'Marcar el canal como leído', ['Escape']],
  ['discord', 3, 'Ir al canal anterior', ['Alt', 'ArrowUp']],
  ['discord', 3, 'Ir al canal siguiente', ['Alt', 'ArrowDown']],
  ['discord', 3, 'Ir al servidor anterior', ['Control', 'Alt', 'ArrowUp']],
  ['discord', 3, 'Ir al servidor siguiente', ['Control', 'Alt', 'ArrowDown']],
  ['discord', 3, 'Abrir el selector de emojis', ['Control', 'e']],
  ['discord', 4, 'Marcar el servidor como leído', ['Shift', 'Escape']],

  ['drive', 1, 'Buscar en Drive', ['/']],
  ['drive', 1, 'Seleccionar todos los elementos', ['Control', 'a']],
  ['drive', 2, 'Renombrar el elemento', ['n']],
  ['drive', 2, 'Ver u ocultar el panel de detalles', ['d']],
  ['drive', 2, 'Abrir el menú "Nuevo"', ['c']],
  ['drive', 3, 'Mover a la papelera', ['Delete']],
  ['drive', 3, 'Copiar', ['Control', 'c']],
  ['drive', 3, 'Pegar', ['Control', 'v']],
  ['drive', 3, 'Deshacer', ['Control', 'z']],
  ['drive', 4, 'Rehacer', ['Control', 'y']],

  ['windows', 1, 'Bloquear la computadora', ['Win', 'l']],
  ['windows', 1, 'Mostrar el escritorio', ['Win', 'd']],
  ['windows', 1, 'Abrir el explorador de archivos', ['Win', 'e']],
  ['windows', 2, 'Cambiar entre aplicaciones', ['Alt', 'Tab']],
  ['windows', 2, 'Abrir la configuración', ['Win', 'i']],
  ['windows', 2, 'Abrir la búsqueda', ['Win', 's']],
  ['windows', 2, 'Minimizar todas las ventanas', ['Win', 'm']],
  ['windows', 2, 'Abrir el menú de enlaces rápidos', ['Win', 'x']],
  ['windows', 3, 'Abrir el administrador de tareas', ['Control', 'Shift', 'Escape']],
  ['windows', 3, 'Captura de pantalla (recorte)', ['Win', 'Shift', 's']],
  ['windows', 3, 'Anclar la ventana a la izquierda', ['Win', 'ArrowLeft']],
  ['windows', 3, 'Abrir el portapapeles', ['Win', 'v']],
  ['windows', 4, 'Crear un escritorio virtual', ['Win', 'Control', 'd']],
  ['windows', 4, 'Cerrar el escritorio virtual', ['Win', 'Control', 'F4']],
  ['windows', 4, 'Ir al escritorio virtual anterior', ['Win', 'Control', 'ArrowLeft']],
  ['windows', 4, 'Ir al escritorio virtual siguiente', ['Win', 'Control', 'ArrowRight']],
];
